---
repos:
    - repo: https://gitlab.com/vojko.pribudic/pre-commit-update
      rev: v0.1.6
      hooks:
          - id: pre-commit-update
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/doublify/pre-commit-rust
      rev: v1.0
      hooks:
          - id: fmt
          - id: cargo-check
